### ISSUE TITLE
Only year supports in time column

### ISSUE THREAD

**Issue by touhi99** [lc5415/raceplotly#8]
Seems like only year number supports. I was trying to plot with Date values in YYYY-MM-DD format, it shows error:

`    for year in range(self.df[self.time_column].min(), self.df[self.time_column].max()+1):                              
TypeError: can only concatenate str (not "int") to str `

Please check

**Comment by lucharo** [comment]
Hello @tapos12 and thanks for pointing that out. I will be working on this tomorrow, do you have a reprex or a dataset I could test this on?

**Comment by touhi99** [comment]
I was trying the covid dataset from python bar_chart_race library:
`https://pypi.org/project/bar-chart-race/`

**Comment by lucharo** [comment]
I've updated the code to work with date format as well as a sequence of numbers, find an example with the bar_chart_race dataset in [example/COVID-DateFormat.py](https://github.com/lc5415/raceplotly/blob/main/example/COVID-DateFormat.py). I've added a date_format argument so that you can use a date format (using strftime) of your choice for whatever date/time sequence you have available. Thanks for the feedback and let me know if you have any further issue.  @tapos12

**Comment by lucharo** [comment]
For your convenience @tapos12: [example in colab](https://colab.research.google.com/drive/1TLZVvkCB5obBOeZsxavFY4J3ZvOBkCez?usp=sharing)
